# Generated by Django 5.0.2 on 2024-02-13 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('leafygreens', 'Leafygreens'), ('root', 'Root'), ('cruciferous', 'Cruciferous'), ('alliums ', 'Alliums'), ('nightshades ', 'Nightshades'), ('squashandgourds', 'Squashandgourds'), ('legumes', 'Legumes')], max_length=30, null=True)),
                ('color', models.CharField(blank=True, choices=[('green', 'Green'), ('orangeandyellow', 'Orangeandyellow'), ('redandpurple', 'Redandpurple'), ('whiteandtan', 'Whiteandtan')], max_length=30, null=True)),
                ('season', models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter')], max_length=30, null=True)),
                ('couisine', models.CharField(blank=True, choices=[('mediterranean', 'Mediterranean'), ('asian', 'Asian'), ('latinamerican', 'Latinamerican'), ('indian', 'Indian')], max_length=30, null=True)),
                ('cooking_method', models.CharField(blank=True, choices=[('raw', 'Raw'), ('steamed', 'Steamed'), ('roasted', 'Roasted'), ('grilled', 'Grilled'), ('stirfried', 'Stirfried'), ('boiled', 'Boiled')], max_length=30, null=True)),
                ('use_case', models.CharField(blank=True, choices=[('salad', 'Salad'), ('soup', 'Soup'), ('sidedish', 'Sidedish'), ('maincourse', 'Maincourse')], max_length=30, null=True)),
                ('nurtitional', models.CharField(blank=True, choices=[('highfiber', 'Highfiber'), ('highprotein', 'Highprotein'), ('lowcarb', 'Lowcarb')], max_length=30, null=True)),
                ('popularity', models.CharField(blank=True, choices=[('mostused', 'Mostused'), ('specialty', 'Specialty'), ('exotic', 'Exotic')], max_length=30, null=True)),
                ('slug', models.SlugField(blank=True, unique_for_date='created_time')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Vegetables/')),
                ('avarage_cost', models.CharField(blank=True, max_length=30, null=True)),
                ('like', models.PositiveIntegerField(default=0)),
                ('seen', models.PositiveIntegerField(default=0)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('key_words', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meal.country')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Meals/')),
                ('text', models.TextField(blank=True, null=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegetable.vegetable')),
            ],
        ),
        migrations.AddIndex(
            model_name='vegetable',
            index=models.Index(fields=['-created_time'], name='vegetable_v_created_46fedc_idx'),
        ),
    ]
