# Generated by Django 5.0.2 on 2024-07-01 10:54

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetable',
            name='color',
        ),
        migrations.RemoveField(
            model_name='vegetable',
            name='cooking_method',
        ),
        migrations.RemoveField(
            model_name='vegetable',
            name='couisine',
        ),
        migrations.RemoveField(
            model_name='vegetable',
            name='nurtitional',
        ),
        migrations.RemoveField(
            model_name='vegetable',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='vegetable',
            name='type',
        ),
        migrations.RemoveField(
            model_name='vegetable',
            name='use_case',
        ),
        migrations.AddField(
            model_name='vegetable',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
