# Generated by Django 5.0.2 on 2024-07-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable', '0002_remove_vegetable_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
