# Generated by Django 5.0.2 on 2024-02-13 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('citrus ', 'Citrus'), ('tropical ', 'Tropical'), ('berries', 'Berries'), ('stone ', 'Stone'), ('melons', 'Melons'), ('drupes', 'Drupes'), ('pome ', 'Pome'), ('exotic ', 'Exotic'), ('dried ', 'Dried'), ('climacteric ', 'Climacteric'), ('nonclimacteric ', 'Nonclimacteric'), ('subtropical ', 'Subtropical'), ('temperate ', 'Temperate'), ('hardy ', 'Hardy'), ('soft ', 'Soft'), ('hard ', 'Hard'), ('juicy ', 'Juicy'), ('aromatic ', 'Aromatic'), ('tart ', 'Tart'), ('sweet ', 'Sweet')], max_length=30, null=True)),
                ('slug', models.SlugField(blank=True, unique_for_date='created_time')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Vegetables/')),
                ('like', models.PositiveIntegerField(default=0)),
                ('seen', models.PositiveIntegerField(default=0)),
                ('avarage_cost', models.CharField(blank=True, max_length=30, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('key_words', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meal.country')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Meals/')),
                ('text', models.TextField(blank=True, null=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruit.fruit')),
            ],
        ),
        migrations.AddIndex(
            model_name='fruit',
            index=models.Index(fields=['-created_time'], name='fruit_fruit_created_0bfbc2_idx'),
        ),
    ]
