# Generated by Django 5.0.2 on 2024-07-01 10:54

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0002_alter_fruit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
