# Generated by Django 5.0.2 on 2024-07-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0003_fruit_title_alter_fruit_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
