# Generated by Django 5.0.2 on 2024-02-13 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('key_words', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('key_words', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('brunch', 'Brunch'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snacks', 'Snacks'), ('desserts', 'Desserts')], max_length=30, null=True)),
                ('dietary_type', models.CharField(blank=True, choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('gluten-free', 'Glutenfree'), ('dairy-free', 'Dairyfree'), ('low-carb', 'Lowcarb'), ('keto-friendly', 'Ketofriendly'), ('paleo', 'Paleo')], max_length=30, null=True)),
                ('cooking_method_type', models.CharField(blank=True, choices=[('grilled', 'Grilled'), ('baked', 'Baked'), ('fried', 'Fried'), ('steamed', 'Steamed'), ('slowcooked', 'Slowcooked'), ('raw', 'Raw')], max_length=30, null=True)),
                ('ingredient_type', models.CharField(blank=True, choices=[('meat', 'Meat'), ('poultry', 'Poultry'), ('seafood', 'Seafood'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('legumes', 'Legumes'), ('grains', 'Grains')], max_length=30, null=True)),
                ('cuisine_type', models.CharField(blank=True, choices=[('italian', 'Italian'), ('french', 'French'), ('japanese', 'Japanese'), ('chinese', 'Chinese'), ('indian', 'Indian'), ('mexican', 'Mexican'), ('thai', 'Thai'), ('greek', 'Greek'), ('moroccan', 'Moroccan')], max_length=30, null=True)),
                ('sepecial_occasion_type', models.CharField(blank=True, choices=[('holidaymeals', 'Holidaymeals'), ('festivemeals', 'Festivemeals'), ('weddingreceptions', 'Weddingreceptions'), ('birthdayparties', 'Birthdayparties'), ('picnics', 'Picnics')], max_length=30, null=True)),
                ('popular_dish_type', models.CharField(blank=True, choices=[('pizza', 'Pizza'), ('sushi', 'Sushi'), ('pasta', 'Pasta'), ('curry', 'Curry'), ('tacos', 'Tacos'), ('burgers', 'Burgers'), ('soups', 'Soups'), ('salads', 'Salads')], max_length=30, null=True)),
                ('slug', models.SlugField(blank=True, unique_for_date='created_time')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Meals/')),
                ('like', models.PositiveIntegerField(default=0)),
                ('seen', models.PositiveIntegerField(default=0)),
                ('avarage_cost', models.CharField(blank=True, max_length=30, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('key_words', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meal.country')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.meal')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meal.region'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Meals/')),
                ('text', models.TextField(blank=True, null=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.meal')),
            ],
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['-created_time'], name='meal_meal_created_dc8937_idx'),
        ),
    ]
