# Generated by Django 5.0.2 on 2024-02-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='recipe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
