# Generated by Django 5.0.2 on 2024-02-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_meal_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='key_words',
            new_name='fruit_key_words',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='key_words',
            new_name='fruit_key_words',
        ),
        migrations.AddField(
            model_name='country',
            name='meal_key_words',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='veg_key_words',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='meal_key_words',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='veg_key_words',
            field=models.TextField(blank=True, null=True),
        ),
    ]
