# Generated by Django 5.0.2 on 2024-03-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_rename_key_words_country_fruit_key_words_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='cuisine_type',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='dietary_type',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='ingredient_type',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='popular_dish_type',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='sepecial_occasion_type',
        ),
        migrations.AlterField(
            model_name='meal',
            name='cooking_method_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
