# Generated by Django 5.0.2 on 2024-03-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0006_meal_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='meal',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
