# Generated by Django 5.0.2 on 2024-07-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0008_remove_meal_cooking_method_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='confirmed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=100),
        ),
    ]
