# Generated by Django 5.0.2 on 2024-02-15 16:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('unique_visits', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
